<?php
/*
 This is a part of project named RestCMS. It is lightweight, extensible and easy to use
 content management system that stands on the idea that server should serve the
 content and clients should give the form to that content.
 
 Copyright (C) 2014  Jan Brejcha
 
 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 any later version.
 
 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.
 
 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
 
/** 
 * Installation wizard for RestCMS system
 */
require_once("bootstrap.php");


//Smarty for MVC for installation scripts and other output needed scripts on server.
require(__DIR__ . '/src/smarty/libs/Smarty.class.php');
$smarty = new Smarty();

$smarty->setTemplateDir(__DIR__ . '/src/smarty/templates');
$smarty->setCompileDir(__DIR__ . '/src/smarty/templates_c');
$smarty->setCacheDir(__DIR__ . '/src/smarty/cache');
$smarty->setConfigDir(__DIR__ . '/src/smarty/configs');
//$smarty->testInstall();


class Installation{
	
	private $smarty;
	
	public function __construct($smarty){
		$this->smarty = $smarty;
	}
	
	private function step1(){
		$timezones = self::getTimezoneArray();
		$project_dir = realpath(dirname(__FILE__));
		
		$this->smarty->assign("timezones", $timezones);
		$this->smarty->assign("project_dir", $project_dir);
		$this->smarty->assign("web_address", "http://" . $_SERVER['HTTP_HOST']);
		$this->smarty->display('install.tpl');
	}
	
	private function install(){
		$PROJECTDIR = mysql_real_escape_string($_POST['PROJECTDIR']);
		$SRCDIRSUFFIX = "/src/cz/brejchajan/restcms";
		$SRCDIR = $PROJECTDIR . $SRCDIRSUFFIX;
		$TIMEZONE = mysql_real_escape_string($_POST['TIMEZONE']);
		$DBTYPE = mysql_real_escape_string($_POST['DBTYPE']);
		$DBNAME = mysql_real_escape_string($_POST['DBNAME']);
		$DBUSER = mysql_real_escape_string($_POST['DBUSER']);
		$DBPASSWORD = mysql_real_escape_string($_POST['DBPASSWORD']);
		$CLIENT_ID = mysql_real_escape_string($_POST['CLIENT_ID']);
		$CLIENT_SECRET = mysql_real_escape_string($_POST['CLIENT_SECRET']);
		/*
		var_dump($PROJECTDIR);
		var_dump($TIMEZONE);
		var_dump($DBTYPE);
		var_dump($DBNAME);
		var_dump($DBUSER);
		var_dump($DBPASSWORD);
		var_dump($CLIENT_ID);
		var_dump($CLIENT_SECRET);
		*/
		
		$configScript = 
"<?php
/**
 * Config file of the RestCMS project, generated by RestCMS installer.
 * Part of the RestCMS project, under GNU/GPLv3 licence.
 */

 /** Timezone settings */
date_default_timezone_set(\"".$TIMEZONE."\");

/** Project */
define(\"PROJECTDIR\", \"".$PROJECTDIR."\");
define (\"SRCDIR\", PROJECTDIR . \"".$SRCDIRSUFFIX."\");
/** Database */
define(\"DBNAME\", \"".$DBNAME."\");
define(\"DBUSER\", \"".$DBUSER."\");
define(\"DBPASSWORD\", \"".$DBPASSWORD."\");
define(\"DBHOST\", \"localhost\");

/** Google Plus **/
const CLIENT_ID = '".$CLIENT_ID."';

const CLIENT_SECRET = '".$CLIENT_SECRET."';

const APPLICATION_NAME = \"RestCMS\";

?>";
	
		$configFile = fopen($SRCDIR . "/config/config.php", "w");
		if ($configFile){
			fwrite($configFile, $configScript);
			fclose($configFile);
			$this->installComplete();		
		}
		else{
			die('Error opening file. Please check the permissions for the directory ' . $SRCDIR . '/config. It must be in a same group
				as your apache is - on linux offten can be changed with <pre>chown nobody:nobody ' . $SRCDIR . '/config</pre>, on OSX change nobody to _www in both cases.');	
		}
	}
	
	private function installComplete(){
		$_POST = array();
		include("src/cz/brejchajan/restcms/config/config.php");
		include("bootstrap.php");
		//update database
		shell_exec('php vendor/bin/doctrine orm:schema-tool:update --force --dump-sql');
		
		$this->smarty->assign("web_address", "http://" . $_SERVER['HTTP_HOST']);
		$this->smarty->assign("CLIENT_ID", CLIENT_ID);
		$this->smarty->display('installComplete.tpl');
	}

	public function run(){
		if ($_POST){
			$this->install();
		}
		else if (!is_file("src/cz/brejchajan/restcms/config/config.php")){
			$this->step1();
		}
		else{
			//config dir exists
			$this->installComplete();
		}
	}
	
	/** 
	 *	Following code for timezone array generation used from:
	 *	http://stackoverflow.com/questions/1727077/generating-a-drop-down-list-of-timezones-with-php
	 * 	Many thanks for good job!
	 */
	private static function getTimezoneArray(){
	    static $timezones = null;

    	if ($timezones === null){
			$timezones = array();
			$offsets = array();
			$now = new DateTime();

			foreach (DateTimeZone::listIdentifiers() as $timezone){
				$now->setTimezone(new DateTimeZone($timezone));
				$offsets[] = $offset = $now->getOffset();
				$timezones[$timezone] = '(' . self::format_GMT_offset($offset) . ') ' . self::format_timezone_name($timezone);
			}

			array_multisort($offsets, $timezones);
		}
		return $timezones;
	}
	
	private static function format_GMT_offset($offset) {
		$hours = intval($offset / 3600);
		$minutes = abs(intval($offset % 3600 / 60));
		return 'GMT' . ($offset ? sprintf('%+03d:%02d', $hours, $minutes) : '');
	}

	private static function format_timezone_name($name) {
		$name = str_replace('/', ', ', $name);
		$name = str_replace('_', ' ', $name);
		$name = str_replace('St ', 'St. ', $name);
		return $name;
	}
}

$installation = new Installation($smarty);
$installation->run();

?>