<?php
/**
 * Example config file.
 * Config file of the RestCMS project, generated by RestCMS installer.
 * Part of the RestCMS project, under GNU/GPLv3 licence.
 */

 /** Timezone settings */
date_default_timezone_set("Europe/Prague");

/** Project */
define("PROJECTDIR", "/Users/janbrejcha/Sites/restcms");
define ("SRCDIR", PROJECTDIR . "/src/cz/brejchajan/restcms");
/** Database */
define("DBNAME", "dbname");
define("DBUSER", "username");
define("DBPASSWORD", "password");
define("DBHOST", "localhost");

/** Google Plus **/
const CLIENT_ID = 'google-client-id';

const CLIENT_SECRET = 'google-client-secret';

const APPLICATION_NAME = "RestCMS";

?>