<?php
/**
 * Config file of the RestCMS project, generated by RestCMS installer.
 * Part of the RestCMS project, under GNU/GPLv3 licence.
 */

 /** Timezone settings */
date_default_timezone_set("Europe/Prague");

/** Project */
define("PROJECTDIR", "/Users/janbrejcha/Web/www/restcms");
define ("SRCDIR", PROJECTDIR . "/src/cz/brejchajan/restcms");
/** Database */
define("DBNAME", "restcms");
define("DBUSER", "root");
define("DBPASSWORD", "brejcha004");
define("DBHOST", "localhost");

/** Google Plus **/
const CLIENT_ID = '965352633379-id8mac0mg6o26qi8v0qdru88tqggh5v4.apps.googleusercontent.com';

const CLIENT_SECRET = '1ue7qfM58xHIghnXZevP6ffM';

const APPLICATION_NAME = "RestCMS";

?>